version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    networks:
      - symfony_network
    volumes:
      - .:/var/www/html/symfony7

  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data:rw
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - symfony_network

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - .:/var/www/html/symfony7
    networks:
      - symfony_network
      
networks:
  symfony_network:
    driver: bridge
